#!/bin/bash
# ==============================================================================
# Gap filling
# ==============================================================================
# Author: Xinxiu Chen
#
# Purpose
# -------
# Fill remaining gaps in the chromosome-level assembly by four
# complementary strategies, using ONT-ultralong reads, HiFi reads,
# cross-assembly complementarity, and manually retrieved high-quality
# reads near each gap.
#
# Main analyses
# -------------
#  1. Gap filling with ONT reads (TGS_Gapcloser)
#  2. Gap filling with LR_Gapcloser (ONT reads / HiFi reads, separately)
#  3. Gap filling by complementarity between assemblies
#     (hifi-only vs ont-only/hifi-ont; nucmer alignment + BLAST validation)
#  4. Gap filling by manually retrieving high-quality reads near the gap
#     (winnowmap alignment + manual curation of mapped reads)
#
# Software and versions
# ---------------------
#   TGS_Gapcloser      (tgsgapcloser, ONT gap filling)
#   LR_Gapcloser       (LR_Gapcloser.sh, long-read gap filling)
#   MUMmer             (nucmer, delta-filter, mummerplot, show-coords)
#   BLAST+             (blastall/blastn)
#   samtools           (faidx)
#   meryl + winnowmap  (repeat-aware long-read mapping)
#   custom scripts     (get_the_detailed_mapping_information_from_bwa_bam_file.pl,
#                       get_mapped_bed.ont.pl, project-specific)
#   NOTE: record exact software versions before publication.
#
# Input files
# -----------
#   $ont (ont.fa)          ONT-ultralong reads/assembly
#   $hifi (hifi.fa)        HiFi reads
#   $ref (genome.hifi.fa)  HiFi-only assembly (gap-closing target)
#   $qry (genome.ont.fa)   ONT-based assembly (complementary source)
#
# Output files
# ------------
#   ${i}_gapfill_r1                        TGS_Gapcloser output
#   ${i}_ont / ${i}_hifi                   LR_Gapcloser outputs
#   ${name}.filter.delta / .filter.coords  MUMmer alignment results
#   gapclosed_fasta.gap_info               gap-flanking coordinates
#   ${chr}_gap.fa / ${chr}_gap.out         gap-region extraction + BLAST validation
#   ${i}.ont.sort.bam (+ .bai)             winnowmap alignments
#   ${i}.ont.sort.bam.info / ${i}_chromosome_map.ont.bed   mapped-read info
#   gap_reads.fa                           reads manually filled into gaps
#
# Notes
# -----
# - Replace /path_to/... with actual paths; ${i} is the sample ID,
#   ${name} is a prefix for MUMmer output.
# - Steps 03-04 involve manual curation: gap_info is generated by
#   organising information near each gap, and reads near gaps are
#   manually retrieved and validated by BLAST. Document these manual
#   steps explicitly in the Methods for reproducibility.
# - -x ava-ont (TGS_Gapcloser) / -W repetitive_k15.txt (winnowmap):
#   repeat-aware mapping requires a precomputed repeat k-mer list
#   (meryl). Keep the exact k and parameters consistent.
# Recommended: record exact software versions before publication.
# ==============================================================================

ont=ont.fa
hifi=hifi.fa
ref=genome.hifi.fa
qry=genome.ont.fa
#### 01.Gap filling by TGS_Gapcloser
tgsgapcloser --scaff $ref  --reads $ont --output ${i}_gapfill_r1 --minmap_arg '-x ava-ont' --thread 22 --min_match 1000 --ne
#### 02.Gap filling by LR_Gapcloser
LR_Gapcloser.sh -i $ref  -l $ont -s n -t 18  -o ${i}_ont
LR_Gapcloser.sh -i $ref  -l $hifi -s n -t 18  -o ${i}_hifi
#### 03.Gap filling by Complementarity between assmeblies using hifi-only, ont-only and hifi-ont
  # Align generating coordination in assemblies
~/miniconda3/bin/nucmer -t 20 --prefix ${name} $ref $qry && delta-filter -1  -q -r -l 15000 ${name}.delta > ${name}.filter.delta && mummerplot -f -s large -t png ${name}.filter.delta -p ${name} && show-coords -THrcl ${name}.filter.delta > ${name}.filter.coords
  #Organize the information near the gap into gapclosed_fasta.gap_info
  #Further validation alignment using BLAST
cat gapclosed_fasta.gap_info | while read i
do
       chr=`echo $i | awk '{print $1}'`
       s=`echo $i | awk '{print $4}'`
       e=`echo $i | awk '{print $5}'`
       s1=$((s-2000))
       e1=$((s-1))
       s2=$((e+1))
       e2=$((e+2000))
        ##echo "chr: $chr, s1: $s1, e1: $e1, s2: $s2, e2: $e2"
       samtools faidx $qry $chr:$s1-$e1 >> ${chr}_gap.fa
       samtools faidx $qry $chr:$s2-$e2 >> ${chr}_gap.fa
       blastall -p blastn -d $ref -i  ${chr}_gap.fa -o  ${chr}_gap.out -F F -m 9 -b 3 -e 1e-5 -a 1
done
  #Manual gap filling using complementary assemblies in no-gap regions
#### 04.Gap filling by manually retrieving high-quality reads near the gap
  # Aligning by winnowmap
meryl count k=15 output merylDB ${ref} && winnowmap -W repetitive_k15.txt -t 30 -ax map-ont $ref $ont | samtools view -F 256 -bS - > ${i}.ont.bam && samtools sort -@ 30 ${i}.ont.bam -o ${i}.ont.sort.bam && samtools index  ${i}.ont.sort.bam && rm  ${i}.ont.bam
  # Extract alignment information from bam Alignment
perl /path_to/get_the_detailed_mapping_information_from_bwa_bam_file.pl ${i}.ont.sort.bam 0 > ${i}.ont.sort.bam.info
perl /path_to/get_mapped_bed.ont.pl ${i}.ont.sort.bam.info ${i}_chromosome_map.ont.bed ${i}_chromosome_maybemap.ont.bed
  # Manual gap filling using reads in the gap regions of ${i}_chromosome_map.ont.bed
samtools faidx $ont gap.reads > gap_reads.fa
  #filling gap_reads.fa to gap region
